### ISSUE TITLE
Frage zur Homey Pro App für Discovergy

### ISSUE THREAD

**Issue by mas12021979** [chriszero/de.zerov.discovergymeter#1]
Hallo Christian,

ich nutze seit 2 Tagen Deine Discovergy App für Homey Pro (early 2019). Kann man irgendwo die Abfrageintervalle einstellen? Aktuell zeigt die App nur ca. alle 5 - 10 Min neue Werte an. Ich benötige eine Echtzeitanzeige um damit meine Wallboxen für ein E-Auto zu steuern.

Danke vorab!

VG!
Markus

**Comment by chriszero** [comment]
Der Abfrageintervall liegt bei 5 Sekunden, könnte man einstellbar machen.
Mit der API von Discovergy gab es die letzten 3 Tage massive Probleme, bzw. immer noch teilweise. Siehe https://forum.discovergy.com/t/api-offline/5272/56

Dann ist noch zu klären ob dein Zähler überhaupt "Sekundenwerte" liefert? Der Standard liefert nur alle 15min einen neuen Zählerstand. Siehst du in der Smartphone-App Sekündlich neue Werte?

**Comment by mas12021979** [comment]
Hallo Christian,

seit gestern geht es wieder schneller. Ja, in der Discovergy-App sehen die Veränderungen im Sekunden-Takt. Das geht wohl bei den Smartmetern von Discovergy wenn sie per LAN angeschlossen sind.

https://user-images.githubusercontent.com/119403062/204756546-710a609d-c951-49f3-8c58-5aec09b802a3.mov

VG!
Markus

**Comment by chriszero** [comment]
Ich kann bei Gelegenheit ein Feature einbauen um den Intervall der Aktualisierung einzustellen.
Grundsätzlich ist das aber niemals "Echtzeit". Die Daten gehen erst zu Discovergy, und dann rufen wir sie ab. Da ist auf alle fälle eine Verzögerung von ein paar Sekunden drin.

Ich mittle den Verbrauch / Einspeisung über einen Zyklus von ~30 Sekunden, und steuere mit diesem "geglättetem" Wert dann Ladesäulen, Akku usw.

Ich habe da momentan ein Projekt (App für Homey) in der Entwicklung, mit dem sich solche Sachen komfortabel über Advanced Flows regeln lassen.

**Comment by chriszero** [comment]
Option in v1.0.4 vorhanden
Testversion: https://homey.app/de-de/app/de.zerov.discovergymeter/Discovergy-Smart-Meter/test/
